# Generated by Django 5.2 on 2025-04-05 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trades', to=settings.AUTH_USER_MODEL)),
                ('offered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_offer', to='barterapp.product')),
                ('requested_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_request', to='barterapp.product')),
            ],
        ),
    ]
