# Generated by Django 5.1.7 on 2025-03-23 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Condition', models.CharField(max_length=50)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OwnerUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestBarter.user')),
            ],
        ),
    ]
